export const CHANGE_TAG="CHANGE_TAG";
export const LIST_TAG="LIST_TAG";
export const GET_TAG_SUCCESS="GET_TAG_SUCCESS";
export const INCREASE_BASKET="INCREASE_BASKET";
export const GET_BASKET_SUCCESS="GET_BASKET_SUCCESS";
export const BASKET_LIST="BASKET_LIST";
export const BASKET_LIST_SUCCESS="BASKET_LIST_SUCCESS";
export const LIST_BASKET="LIST_BASKET";
export const SEARCH_STRING="SEARCH_STRING";
export const SEARCH_STRING_SUCCSESS="SEARCH_STRING_SUCCSESS";
export const TAG_COLORS="TAG_COLORS";
export const TAG_COLORS_SUCCESS="TAG_COLORS_SUCCESS";
export const TAG_BRANDS="TAG_BRANDS";
export const TAG_BRANDS_SUCCESS="TAG_BRANDS_SUCCESS";

