const products ={
    phones : [
        {
            productID:  "1",
            title : "Apple Iphone 11",
            brand : "Apple",
            color : "Kırmızı",
            createdDate: "2021-02-12T00:00:00+3:00",
            discountedprice: 90.85,
            price: "124,00 TL",
            discountRate: "12%",
            img:"./images/iphoneRed.png",
        },
        {
            productID : "2",
            title : "Apple Iphone 12",
            brand : "Apple",
            color : "Siyah",
            createdDate: "2021-05-11T00:00:00+3:00",
            discountedprice: 800.85,
            price: "900,85 TL",
            discountRate: "2%",
            img:"./images/iphoneBlack.png",
        },
        {
            productID:  "3",
            title : "Apple Iphone 11",
            brand : "Apple",
            color : "Sarı",
            createdDate: "2021-03-12T00:00:00+3:00",
            discountedprice: 80.85,
            price: "90,85 TL",
            discountRate: "2%",
            img:"./images/iphoneYellow.png",
        },
        {
            productID : "4",
            title : "Apple Iphone 12",
            brand : "Apple",
            color : "Pembe",
            createdDate: "2021-03-11T00:00:00+3:00",
            discountedprice: 155.85,
            price: "224,85 TL",
            discountRate: "12%",
            img:"./images/iphonePink.png",
        },
        {
            productID : "5",
            title : "Samung S20",
            brand : "Samsung",
            color : "Siyah",
            createdDate: "2021-06-11T00:00:00+3:00",
            discountedprice: 1553.85,
            price: "3224,85 TL",
            discountRate: "12%",
            img:"./images/SamsungS20.jpg",
        },
        {
            productID : "6",
            title : "Huawei P40 Pro",
            brand : "Huawei",
            color : "Mavi",
            createdDate: "2021-01-11T00:00:00+3:00",
            discountedprice: 1555.85,
            price: "224,85 TL",
            discountRate: "12%",
            img:"./images/huaweiP402.jpg",
        },
        {
            productID : "7",
            title : "Huawei P40 Pro",
            brand : "Huawei",
            color : "Siyah",
            createdDate: "2021-01-11T00:00:00+3:00",
            discountedprice: 1555.85,
            price: "224,85 TL",
            discountRate: "12%",
            img:"./images/huaweiP40.jpg",
        },
        {
            productID:  "8",
            title : "Apple Iphone 12",
            brand : "Apple",
            color : "Kırmızı",
            createdDate: "2021-02-10T00:00:00+3:00",
            discountedprice: 902.85,
            price: "124,00 TL",
            discountRate: "12%",
            img:"./images/iphoneRed2.png",
        },
        {
            productID : "9",
            title : "Apple Iphone 11",
            brand : "Apple",
            color : "Pembe",
            createdDate: "2021-07-11T00:00:00+3:00",
            discountedprice: 5557.85,
            price: "224,85 TL",
            discountRate: "12%",
            img:"./images/iphonePink2.jpg",
        },
        {
            productID : "10",
            title : "Samung S10",
            brand : "Samsung",
            color : "Mavi",
            createdDate: "2021-06-11T00:00:00+3:00",
            discountedprice: 3553.85,
            price: "3224,85 TL",
            discountRate: "12%",
            img:"./images/SamsungS202.jpg",
        },
        {
            productID : "11",
            title : "Huawei P40 Pro",
            brand : "Huawei",
            color : "Siyah",
            createdDate: "2021-01-11T00:00:00+3:00",
            discountedprice: 1255.85,
            price: "224,85 TL",
            discountRate: "12%",
            img:"./images/huaweiP402.jpg",
        },
        {
            productID : "12",
            title : "Apple Iphone XR",
            brand : "Apple",
            color : "Kırmızı",
            createdDate: "2021-08-11T00:00:00+3:00",
            discountedprice: 6525.85,
            price: "224,85 TL",
            discountRate: "12%",
            img:"./images/iphoneXr.png",
        },
        {
            productID : "13",
            title : "Apple Iphone 13",
            brand : "Apple",
            color : "Pembe",
            createdDate: "2021-02-11T00:00:00+3:00",
            discountedprice: 16525.85,
            price: "224,85 TL",
            discountRate: "12%",
            img:"./images/iphone13pink.jpg",
        },        
    ]
}

export default products;